### ISSUE TITLE
Typedoc: research

### ISSUE THREAD

**Issue by tatarianBarbarian** [evilmartians/astro-typedoc#3]
[TypeDoc](https://typedoc.org/) seems to be a good candidate for generating documentation from type definitions and TSDoc comments.

I need to check its input formats, output formats, and restrictions.

---

TODO:

- [x] Go through docs
- [x] Run TypeDoc on some TS projects
- [x] Check outputs
- [x] Try modifying outputs
- [x] Check `ai`'s scripts

**Comment by ai** [comment]
Here is my scripts to compile `TypeDoc` to AST and then generate HTML from AST:

https://github.com/logux/logux.org/blob/main/scripts/steps/build-api.js
https://github.com/postcss/postcss.org/blob/main/scripts/build-api.js

Note that this approach works not perfect. It brakes every time because I didn’t cover all possible combinations of types.
